### ISSUE TITLE
请问大神能上传一份ios的demo 吗？

### ISSUE THREAD

**Issue by anita-anita** [Old-Driver-HZ-Branch/cordova-plugin-umengsdk#1]
1. cordova create cordovaUmengDemo com.zmtxapp.umeng cordovaUmengDemo
2. cordova platforms add ios
3. cd  cordovaUmengDemo
4. cordova build ios
我用这四部创建的demo那个最外层的www/index.html和www/js/index.js中不知道怎么写

**Comment by iVanPan** [comment]
@anita-anita  就直接在index.js 里面直接调用MobclickAgent.init('xxxxxxxxx'); 这几个方法就好了

**Comment by anita-anita** [comment]
MobclickAgent.init('xxxxxxxxx');这个xxxxxxxxx填写什么？我看init中需要两个参数
 /**
     * 初始化
     * @param appKey appKey
     * @param channelId 渠道号
     */
	init:function(appKey,channelId) {
        cordova.exec(null, null, "Umeng", "init", [appKey, channelId]);
    },

**Comment by iVanPan** [comment]
@anita-anita  就 AppKey 和 渠道号，在 iOS 上面不传channelId 没有关系的，不传 默认就是 App Store。所以简单点就是MobclickAgent.init('你的AppKey');

**Comment by anita-anita** [comment]
我在那里打断点不进，您帮我看看MobclickAgent.init('你的AppKey');这个方法加的位置对吗？
<img width="633" alt="456" src="https://cloud.githubusercontent.com/assets/10149972/26093247/9fb26808-3a47-11e7-9b10-537a91c69c62.png">

**Comment by iVanPan** [comment]
@anita-anita  MobclickAgent.init('你的AppKey'); 放在onDeviceReady 这个方法里面，第30行的后面。

**Comment by iVanPan** [comment]
@anita-anita  cordova 插件一般要在 onDeviceReady 以后才能加载插件，你要测试把方法加载在onDeviceReady方法里面进行测试

**Comment by anita-anita** [comment]
进断点了，谢谢，插件的Umeng.js中别的方法也是放在onDeviceReady 这个方法里面，第30行的后面吧？

**Comment by iVanPan** [comment]
@anita-anita  麻烦自己看 Umeng 文档

**Comment by anita-anita** [comment]
灰常感谢！
